title: PointNetGPD Detecting Grasp Configurations from Point Sets
description: Hongzhuo Liang*, Xiaojian Ma*, Shuang Li, Michael Görner, Song Tang, Bin Fang, Fuchun Sun, Jianwei Zhang
show_downloads: false
theme: jekyll-theme-cayman
github:
  is_project_page: false
